BlogProject/BlogProject/urls.py
from blog_app.views import HomeView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='index'),
    path('blog/', include('blog_app.urls')),
    path('comment/', include('comment_app.urls')),
]

BlogProject/blog_app/urls.py
from django.urls.conf import include
from blog_app.views import BlogCommentDeleteView, BlogCommentUpdateView, BlogCommentView, BlogCommentViewset, BlogDetailView, BlogListView, BlogViewset, UserViewset
from django.urls import path
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'blog_api',BlogViewset, basename='blog_api')
router.register(r'blog_comment_api',BlogCommentViewset, basename='blog_comment_api')
router.register(r'user_api',UserViewset, basename='user_api')

urlpatterns = [
        path('', BlogListView.as_view(), name='blog_list'),
        path('',include(router.urls)),
        path('detail/<str:pk>', BlogDetailView.as_view(), name='blog_detail'),
        path('create', BlogCommentView.as_view(), name='create_blogcomment'),
        path('update/<int:pk>',BlogCommentUpdateView.as_view() , name='update_blogcomment'),
        path('delete/<int:pk>',BlogCommentDeleteView.as_view() , name='delete_blogcomment'),
        
        
        ]

BlogProject/blog_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
   username = models.CharField(max_length = 100, primary_key = True) 
   first_name = models.CharField(max_length = 50)
   last_name = models.CharField(max_length = 50)
   email = models.EmailField()
   password = models.CharField(max_length = 50)

   def __str__(self):
       return self.username

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    content = models.CharField(max_length = 1000)
    created_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='blog-images/', null=True, blank=True)

    def __str__(self):
        return f"{self.author}:{self.title}"

class BlogComment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.CharField(max_length = 1000)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.blog}:{self.content}"
    

BlogProject/blog_app/forms.py
from django import forms
from .models import Blog, BlogComment

class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']


class BlogCommentForm(forms.ModelForm):

    class Meta:
        model = BlogComment
        fields = ['content']

BlogProject/blog_app/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, TemplateView
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import BlogCommentForm
from .models import Blog, BlogComment, User
from django.core import serializers
from django.views import View

from rest_framework import viewsets
from .serializers import BlogSerializer,UserSerializer,BlogCommentSerializer
# Create your views here.

class HomeView(TemplateView):
    template_name = 'blog/index.html'


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/list.html'
    queryset = Blog.objects.all().order_by('-created_date')
    context_object_name = 'blogs'

class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/detail.html'
    context_object_name = 'blog'

    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['comments'] = BlogComment.objects.filter(blog=self.object).order_by('-created_date')
        context['form'] = BlogCommentForm()
        return context

class BlogCommentView(View):
    def post(self, request, *args, **kwargs):

        blog_id = request.POST.get('blog_id')
        blog = Blog.objects.get(id=blog_id)
        data = request.POST.dict()
        data.pop('blog_id')
        data['blog'] = blog

        form = BlogCommentForm(data)
        if form.is_valid():
            # Model.save() does either INSERT or UPDATE of an object in a DB, while Model.objects.create() does only INSERT.
            comment= BlogComment(blog=blog,content=data['content'])
            comment.save()
            ser_instance = serializers.serialize('json', [comment,]) # list of dictionary with necessary info
            return JsonResponse({'instance': ser_instance,})

class BlogCommentUpdateView(UpdateView):
    model = BlogComment
    fields = ['content']        
    template_name = 'blog/edit.html'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data( **kwargs)
        context['id'] = self.object.pk
        return context

    def post(self, request, *args, **kwargs):
        comment_id = request.POST.get('comment_id')
        comment = BlogComment.objects.get(id=comment_id)
        # getting only required field for BlogCommentForm
        blog_id = request.POST.get('blog_id')
        blog = Blog.objects.get(id=blog_id)
        data = request.POST.dict()
        data.pop('blog_id')
        data.pop('comment_id')
        data['blog'] = blog
        print('from post')
        print(request.POST)

        print(comment)
        form = BlogCommentForm(data, instance=comment)
        if form.is_valid():
            # Model.save() does either INSERT or UPDATE of an object in a DB, while Model.objects.create() does only INSERT.
            comment = form.save()
            ser_instance = serializers.serialize('json', [comment,]) # list of dictionary with necessary info
            return JsonResponse({'instance': ser_instance,})       
            #return JsonResponse({'instance': 'hello'})       

    
class BlogCommentDeleteView(DeleteView):
    
    def post(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        comment = get_object_or_404(BlogComment,pk=pk)
        comment.delete()
        return JsonResponse({'instance': 'hello'})       
                

#class BlogCommentCreateView(CreateView):
#    model = BlogComment
#    template_name = 'blog/create.html'
#    fields = ['blog','content']
#    success_url = '/'
#
#    def form_valid(self, form):
#        print('form_valid')
#        instance = form.save()
#        # how to get blog_obj
#        #comments = list(BlogComment.objects.filter(blog=blog_obj).order_by('-created_date'))
#        ser_instance = serializers.serialize('json', [instance,]) # list of dictionary with necessary info
#        #ser_instance = serializers.serialize('json', comments) # list of dictionary with necessary info
#        #print(instance)
#        #print(ser_instance)
#        return JsonResponse({'instance':ser_instance})
#        
#    def form_invalid(self, form):
#        print('form invalid')
#        return super().form_invalid(form)

#class GetBlogAjaxView(View):
#    def get(self, request, *args, **kwargs):
#        blog_id = self.request.GET.get('blog_id')
#        print('blog_id',blog_id)
#        blog = Blog.objects.filter(id=blog_id)
#        print('blog',blog[0])
#        print(type(blog[0]))
#
#        return JsonResponse({'blog':blog[0].title}, safe=False)



## for rest api
class BlogViewset(viewsets.ModelViewSet):
    serializer_class = BlogSerializer
    queryset = Blog.objects.all()

class UserViewset(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

class BlogCommentViewset(viewsets.ModelViewSet):
    serializer_class = BlogCommentSerializer
    queryset = BlogComment.objects.all()

BlogProject/blog_app/templates/blog/create.html
{% extends 'base.html' %}
{%block title%}
<title>Create</title>
{%endblock title%}

{% block content %}
<form action="" method='POST'>
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>
{% endblock content %}

BlogProject/blog_app/templates/blog/delete.html
{% extends 'base.html' %}
{%block title%}
{%endblock title%}

{% block content %}
    <h1> Delete Post </h1>
    <form method="post" >
        {% csrf_token %}
        <p>Are you sure you want to delete post "{{ student }}"?</p>
        <input type="submit" value="confirm">
    </form>
{% endblock content %}

BlogProject/blog_app/templates/blog/detail.html
{% extends 'base.html' %}
{%block title%}
{%endblock title%}

{% block content %}
<h3>Title: {{blog.title}}</h3>
<hr>
<p>{{blog.content}}</p>
<hr>
<h3><i>By {{blog.author}}</i></h3>
<hr>

<form action="" id='comment_form' method='POST'>
    {%csrf_token%}
    {{form.as_p}}
    <button id='submit' name='submit' type="submit" class="btn btn-primary" >Comment</button>
</form>

<hr>
<h4>Comments</h4>
<div class="comments">
<table>
    <thead>
        <th></th>
        <th></th>
    </thead>
<tbody>
{% for comment in comments %}
        <tr id='comment-{{comment.id}}'>
            <td id={{comment.id}}>{{comment.content}}</td>
            <td><button id={{comment.id}} type="button" class="btn btn-primary edit" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</button></td>
            <td><button id={{comment.id}} type='button' class='bth btn-primary delete'>Delete</button></td>
        </tr>
{%endfor%}
</tbody>
<hr>
</div>



<!-- Modal -->
<div class="modal fade" id="CommentModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>




<script>
function clear(form){
    // this function clear the value in placeholder after form submission.
    //form.querySelector('#id_content').forEach((element)=> element.value='');
    
    form.querySelector('input[name="content"]').value='';
}
//$(document).ready(function(){});
    // creating comment 
    // Since Comment has Blog as Foreign key we need the Blog instance to create Comment instance
    // i.e to which blog a comment belong to so for that we sent the blog id to query required blog 
    // and create comment instance for that blog
    $("#comment_form").on('submit',function(event){
       // console.log(this)
        let form = this
        event.preventDefault();
       // console.log(event);

        let formData = new FormData(this);
        //var data = JSON.stringify(Object.fromEntries(formData));
        let data = Object.fromEntries(formData);
        //let blog_obj = {{blog}};
        let blog_id = '{{blog.id}}';
        //console.log('blog_id',blog_id);
        //console.log(blog_obj);
        //data['blog'] = blog_obj;
        data['blog_id'] = blog_id;
        //console.log(data);
        //console.log(typeof(data));
            
        $.ajax({
            url:"{% url 'create_blogcomment' %}",
            data: data,
            method:"POST",
            success: function(response){
                console.log('After successful ajax call.')
                let instance = JSON.parse(response['instance']);
                let comment = instance[0]['fields']['content'];
                let comment_id = instance[0]['pk']
                let edit = `<td><button id=${comment_id} type="button" class="btn btn-primary edit" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</button></td>`
                let del = `<td><button id=${comment_id} type="button" class='bth btn-primary delete'>Delete</button></td>`
                console.log(response)

                let row = `<tr id='comment-${comment_id}'><td id=${comment_id}>`+comment+'</td>'+edit+del+'</tr>';
                $('tbody').prepend(row);
                clear(form);

            }
        })      
  });
//For displaying update form
$('.comments').on('click','.edit',function(event){
    //event.preventDefault()
    console.log('from edit')
    comment_id = $(this).attr('id')
    url = "{% url 'update_blogcomment' 1234 %}".replace(1234,comment_id),
        $.get(url, function(response){
            $('#CommentModal').modal('show')
            $('.modal-body').empty().append(response)

        })
})

//updating comment in database and html page
// for updating it is important to know which comment is being update and which blog it belongs to.
// we select the required comment and update it in database and html page.
// for updating in database we sent the pk of blog from post request and in the view we query required blog
// and create comment instance of particular blog and update
$('.modal-body').on('submit','.update_form', function(event){
    console.log($(this).attr('id'))
    comment_id = $(this).attr('id')
    url = "{% url 'update_blogcomment' 1234 %}".replace(1234,comment_id),
    console.log(url)
    event.preventDefault();
    // console.log(event);

    let formData = new FormData(this);
    //var data = JSON.stringify(Object.fromEntries(formData));
    let data = Object.fromEntries(formData);
    //let blog_obj = {{blog}};
    let blog_id = '{{blog.id}}';
    //console.log('blog_id',blog_id);
    //console.log(blog_obj);
    //data['blog'] = blog_obj;
    data['blog_id'] = blog_id;
    data['comment_id'] = comment_id;
    console.log(data);
    //console.log(typeof(data));
        
    $.ajax({
        url:url,
        data: data,
        method:"POST",
        success: function(response){
            console.log('After successful Update ajax call.')
            $('#CommentModal').modal('hide')

            //console.log(response)
            let instance = JSON.parse(response['instance']);
            let comment = instance[0]['fields']['content'];
            let comment_id = instance[0]['pk']
            //console.log("updated",comment)
            
            let edit = `<td><button id=${comment_id} type="button" class="btn btn-primary edit" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</button></td>`
            let del = `<td><button id=${comment_id} type="button" class='bth btn-primary delete'>Delete</button></td>`
            //console.log(response)

            let row = `<tr id='comment-${comment_id}'><td id=${comment_id}>`+comment+'</td>'+edit+del+'</tr>';
            // first removing the old comment and adding new comment 
            $('tbody').find(`#comment-${comment_id}`).remove()

            $('tbody').prepend(row);
            //$('tbody').prepend(row);

        }
    })      

})
$('tbody').on('click','.delete', function(event){

    console.log(this)
    comment_id = $(this).attr('id')
    url = "{% url 'delete_blogcomment' 1234 %}".replace(1234,comment_id),
    console.log('gg')
    $.ajax({
        url:url,
        data: {

            csrfmiddlewaretoken: "{{csrf_token}}"
        },
        method:"POST",
        success: function(response){
            console.log('After successful Delete ajax call.')
            
                console.log(this)
            console.log(response)
            
            $('tbody').find(`#comment-${comment_id}`).remove()
            //$('tbody').prepend(row);

        }
    })      
})
</script>
{% endblock content %}

BlogProject/blog_app/templates/blog/edit.html
{% block content %}
<form action="" method="POST" id={{id}} class='update_form'>
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Save">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</form>
{% endblock content %}

BlogProject/blog_app/templates/blog/index.html
{% extends 'base.html' %}
{%block title%}
{%endblock title%}

{% block content %}
    <p>This is a Blog Project with CRUD on comments using AJAX.</p>
    <p>Go to Blogs and comment on blog to try it out.</p>
{% endblock content %}

BlogProject/blog_app/templates/blog/list.html
{%extends 'base.html'%}
{%block title%}
<title>Home</title>
{%endblock title%}

{% block content %}
    
<table>
    <thead>
        <th>Title</th>
        <th>Author</th>
    </thead>
<tbody>
{% for blog in blogs %}
        <tr>
            <td><b><a href="{% url 'blog_detail' blog.pk%}">{{blog.title}}</a></b></td>
            <td><i>{{blog.author}}</i></td>
        </tr>
{%endfor%}
</tbody>
</table>
{% endblock content %}